# Generated by Django 5.1.6 on 2025-03-23 18:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chefprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chefprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/default_profile.png', null=True, upload_to=api.models.chef_picture_upload_path),
        ),
    ]
