# Generated by Django 5.1.6 on 2025-03-25 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_chefprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, default='defaults/default_dish.png', null=True, upload_to='dish_pictures/')),
                ('description', models.TextField()),
                ('available_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('serving_number', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('chef', models.ForeignKey(limit_choices_to={'role': 'chef'}, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
