# Generated by Django 5.1.6 on 2025-04-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_chefprofile_full_name_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(default='defaults/default_dish.png', upload_to='dish_pictures/'),
        ),
    ]
