# Generated by Django 5.1.6 on 2025-04-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dish',
        ),
        migrations.AddField(
            model_name='booking',
            name='dishes',
            field=models.ManyToManyField(related_name='bookings', to='api.dish'),
        ),
    ]
