# Generated by Django 5.1.6 on 2025-04-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_booking_dish_booking_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='time_range_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='time_range_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
