# Generated by Django 5.1.6 on 2025-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dish_time_range_end_dish_time_range_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('awaiting_payment', 'Awaiting Payment'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
