# Generated by Django 5.1.6 on 2025-04-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
