# Generated by Django 5.1.6 on 2025-05-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='breakfast_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='dinner_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='lunch_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='pre_booking_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='urgent_booking_available',
            field=models.BooleanField(default=True),
        ),
    ]
