# Generated by Django 5.1.6 on 2025-05-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_chefrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
